# Generated by Django 5.2 on 2025-04-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=15)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
