# Generated by Django 5.2 on 2025-04-20 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_category_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="cateogry",
            new_name="category",
        ),
    ]
